### ISSUE TITLE
Clarify support for virtual desktops

### ISSUE THREAD

**Issue by Poopooracoocoo** [valinet/WinOverview2#3]
Your readme doesn't say anything about whether this interacts with virtual desktops

**Comment by valinet** [comment]
It does not. Idk if it still works anymore... As can be seen from the screenshot, it shows no virtual desktops...

**Comment by Poopooracoocoo** [comment]
Mind adding that (it may not work anymore and that it doesn't support virtual desktops) to the readme? :) thanks! you're awesome and i hope you have an awesome day!! 

i have maybe watched too much parks and rec and have turned into chris traeger

**Comment by valinet** [comment]
I don't want to necessarily bump this project again to the top of the list... and what is the point of adding a "maybe"? That's kind of understood, like, it does not bring any new information to the user...

**Comment by Poopooracoocoo** [comment]
understood! :)
